### ISSUE TITLE
Issues with Teradata?

### ISSUE THREAD

**Issue by thomasnield** [davidmoten/rxjava-jdbc#43]
I'm not sure whether to post this problem here or in the HikariCP page. I am trying to use Teradata which works just fine as shown below. (EDIT: Not fine, after iterating records it acts like `onCompleted()` is never called)
```
Database.builder()
.url("jdbc:teradata://CSEDW/database=edw_prod_vw,logmech=TD2")
.username(myUserName)
.password(myPassword)
```

But the moment I try to pool() the connections I start to have problems
```
Database.builder()
.url("jdbc:teradata://CSEDW/database=my_db_env,logmech=TD2")
.username(myUserName)
.password(myPassword)
.pool(2,5);
```

I get the following stacktrace
```
com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization: Connection.isValid() is not supported, configure connection test query.
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:581)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:152)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
	at com.github.davidmoten.rx.jdbc.ConnectionProviderPooled.get(ConnectionProviderPooled.java:80)
	at com.github.davidmoten.rx.jdbc.QuerySelectOnSubscribe.connectAndPrepareStatement(QuerySelectOnSubscribe.java:105)
	at com.github.davidmoten.rx.jdbc.QuerySelectOnSubscribe.call(QuerySelectOnSubscribe.java:64)
	at com.github.davidmoten.rx.jdbc.QuerySelectOnSubscribe.call(QuerySelectOnSubscribe.java:19)
	at rx.Observable.unsafeSubscribe(Observable.java:7531)
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
	at rx.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:80)
	at rx.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:59)
	at rx.internal.operators.OperatorSubscribeOn$1.onNext(OperatorSubscribeOn.java:57)
	at rx.internal.operators.OperatorSubscribeOn$1.onNext(OperatorSubscribeOn.java:43)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:43)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:32)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.unsafeSubscribe(Observable.java:7531)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.subscribeNext(OperatorConcat.java:176)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:140)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:79)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
	at rx.observers.SerializedObserver.onNext(SerializedObserver.java:159)
	at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:95)
	at rx.internal.operators.OperatorConcat$ConcatInnerSubscriber.onNext(OperatorConcat.java:206)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:43)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:32)
	at rx.Observable.unsafeSubscribe(Observable.java:7531)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.subscribeNext(OperatorConcat.java:176)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:140)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:79)
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:106)
	at rx.Subscriber.setProducer(Subscriber.java:177)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:50)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:33)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.subscribe(Observable.java:7621)
	at rx.Observable.subscribe(Observable.java:7397)
	at com.swa.rm.od.AirportConversionMapping.main(AirportConversionMapping.java:32)
Caused by: java.sql.SQLException: Connection.isValid() is not supported, configure connection test query.
	at com.zaxxer.hikari.pool.PoolElf.setupConnection(PoolElf.java:178)
	at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:497)
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:565)
	... 46 more
```

How do I configure Teradata into this?

**Comment by thomasnield** [comment]
Pooling aside, I'm noticing some bizarre behavior that acts like the resultset never calls `onCompleted()`. It will sometimes block infinitely or will take a moment and then not output anything.

myDb.select("select * from MY_TABLE")
.count().subscribe(System.out::println, e -> e.printStackTrace());

**Comment by davidmoten** [comment]
Interesting. I haven't used Teradata. Can you debug this one?

**Comment by thomasnield** [comment]
Sure, Teradata is our central data platform so I'm afraid I don't have a choice! I'll see if I can get to the bottom of it.

**Comment by thomasnield** [comment]
Debugging it right now and trawling through source code. I'm curious, is there no API interface to provide one's own `HikariDataSource`? Your `ConnectionProviderPooled` class seems to indicate no.

**Comment by thomasnield** [comment]
It turned out we were using a very old Teradata JDBC library. I downloaded and upgraded to the latest version.
https://downloads.teradata.com/download/connectivity/jdbc-driver

Afterwards everything worked great. `onCompleted()` got called and everything.
