### ISSUE TITLE
Problems with SQLite and File-locking

### ISSUE THREAD

**Issue by thomasnield** [davidmoten/rxjava-jdbc#45]
Hi David, 
I've been playing a lot with SQLite and RxJava-JDBC this weekend. This may just be a limitation of SQLite and the fact it is serverless and file-based, so obviously it has a limitation with concurrent file-locking . 

Suppose I create a SQLite database with these two simple tables, where `TABLE_ONE` is the parent and `TABLE_TWO` is the child.  
```
CREATE TABLE TABLE_ONE (
    ID    INTEGER PRIMARY KEY
                  NOT NULL,
    VALUE INTEGER NOT NULL
);

CREATE TABLE TABLE_TWO (
    ID         INTEGER NOT NULL
                       PRIMARY KEY,
    FOREIGN_ID INTEGER NOT NULL
                       REFERENCES TABLE_ONE ([KEY]),
    VALUE      INTEGER NOT NULL
);
```
I then create an RxJava-JDBC procedure to insert a record into `TABLE_ONE`, and reactively take the new ID and use it to populate a `TABLE_TWO` record. 
```
public final class Launcher {

    public static void main(String[] args) {

       final Database db = Database.builder()
                .url("jdbc:sqlite:C:/Users/Thomas/test.db")
                .pool(1, 5)
                .build();

        db.update("INSERT INTO TABLE_ONE (VALUE) VALUES (100)")
                .returnGeneratedKeys()
                .getAs(Integer.class)
                .flatMap(k -> db.select("SELECT * FROM TABLE_ONE WHERE ID = ?")
                        .parameter(k)
                        .get(rs -> new Type1(rs.getInt("ID"), rs.getInt("VALUE")))
                ).flatMap(t1 -> db.update("INSERT INTO TABLE_TWO (FOREIGN_ID,VALUE) VALUES (?,?)")
                        .parameter(t1.id)
                        .parameter(t1.value)
                        .returnGeneratedKeys()
                        .getAs(Integer.class)
                ).flatMap(k -> db.select("SELECT * FROM TABLE_TWO WHERE ID = ?")
                        .parameter(k)
                        .get(rs -> new Type2(rs.getInt("ID"), rs.getInt("FOREIGN_ID"), rs.getInt("VALUE")))

        ).subscribe(System.out::println, Throwable::printStackTrace);
    }
    private static final class Type1 {
        private final int id;
        private final int value;
        private Type1(int id, int value) {
            this.id = id;
            this.value = value;
        }
    }
    private static final class Type2 {
        private final int id;
        private final int foreignId;
        private final int value;
        private Type2(int id, int foreignKey, int value) {
            this.id = id;
            this.foreignId = foreignKey;
            this.value = value;
        }
        @Override
        public String toString() {
            return "Type2{" +
                    "id=" + id +
                    ", foreignId=" + foreignId +
                    ", value=" + value +
                    '}';
        }
    }
}
```
The insertion for `TABLE_ONE` executes successfully. But when the second insertion for `TABLE_TWO` occurs I get a classic SQLite `[SQLITE_BUSY]` error. 

```
Caused by: java.sql.SQLException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at org.sqlite.core.DB.newSQLException(DB.java:890)
	at org.sqlite.core.DB.newSQLException(DB.java:901)
	at org.sqlite.core.DB.execute(DB.java:807)
	at org.sqlite.core.DB.executeUpdate(DB.java:847)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:86)
	at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61)
	at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.executeUpdate(HikariPreparedStatementProxy.java)
	at com.github.davidmoten.rx.jdbc.QueryUpdateOnSubscribe.performUpdate(QueryUpdateOnSubscribe.java:225)
	... 309 more
```
I had a theory that the monad was to blame and the `onCompleted()` was never called after the first INSERT, causing the connection/file to still be occupied and locked. So on the second INSERT,  the statement was not yet closed from the first INSERT, causing the `[SQLITE_BUSY]` error. 

I think my theory proved correct. When I blocked the first INSERT and pulled the resulting first object out of the monad, I was able to successfully use it to drive the second INSERT. 

```
       final Database db = Database.builder()
                .url("jdbc:sqlite:C:/Users/Thomas/test.db")
                .pool(1, 5)
                .build();

        Type1 type1 = db.update("INSERT INTO TABLE_ONE (VALUE) VALUES (100)")
                .returnGeneratedKeys()
                .getAs(Integer.class)
                .flatMap(k -> db.select("SELECT * FROM TABLE_ONE WHERE ID = ?")
                        .parameter(k)
                        .get(rs -> new Type1(rs.getInt("ID"), rs.getInt("VALUE")))
                ).toBlocking().first();

                db.update("INSERT INTO TABLE_TWO (FOREIGN_ID,VALUE) VALUES (?,?)")
                        .parameter(type1.id)
                        .parameter(type1.value)
                        .returnGeneratedKeys()
                        .getAs(Integer.class)
                        .flatMap(k -> db.select("SELECT * FROM TABLE_TWO WHERE ID = ?")
                                .parameter(k)
                                .get(rs -> new Type2(rs.getInt("ID"), rs.getInt("FOREIGN_ID"), rs.getInt("VALUE")))
                        ).subscribe(System.out::println, Throwable::printStackTrace);

```
Obviously this is not an optimal workaround because we don't want to break the monad. Considering SQLite is such a ubiquitous database solution especially with Android developers, I propose we remedy this if possible. I can try to help if we want to investigate this. 

What do you think?

**Comment by thomasnield** [comment]
I found a somewhat effective workaround, although I'm curious if a better way is proposed. If I add `.toList().flatMap(Observable::from)` operators between the two operations, the `toList()` can block until all INSERTs are gathered and completed. Then the resulting list can be flattened with an `.flatMap(Observable::from)` and continue the next INSERT. 

```
 db.update("INSERT INTO TABLE_ONE (VALUE) VALUES (100)")
                .returnGeneratedKeys()
                .getAs(Integer.class)
                .flatMap(k -> db.select("SELECT * FROM TABLE_ONE WHERE ID = ?")
                                .parameter(k)
                                .get(rs -> new Type1(rs.getInt("ID"), rs.getInt("VALUE")))
                )
                .toList().flatMap(Observable::from)
                .flatMap(t1 -> db.update("INSERT INTO TABLE_TWO (FOREIGN_ID,VALUE) VALUES (?,?)")
                                .parameter(t1.id)
                                .parameter(t1.value)
                                .returnGeneratedKeys()
                                .getAs(Integer.class)
                )
                .flatMap(k -> db.select("SELECT * FROM TABLE_TWO WHERE ID = ?")
                                .parameter(k)
                                .get(rs -> new Type2(rs.getInt("ID"), rs.getInt("FOREIGN_ID"), rs.getInt("VALUE")))

                ).subscribe(System.out::println, Throwable::printStackTrace);
```

**Comment by thomasnield** [comment]
After some thinking, I thought about closing this PR since this limitation of SQLite feels at odds with the reactive paradigm. I can't really think of a way to inherently support concurrent writes that isn't at odds with the reactive protocol. The toList() workaround or some leveraging of materialize()/dematerialize() may offer a decent solution that adheres to the Observable contract. However there really is no way to avoid blocking short of executing and closing each INSERT individually.

SQLite is unlike other database platforms in that it is anti-concurrent with write operations. It's probably wrong to change the architecture just for SQLite unless we created an alternate implementation for it with an existing interface.

**Comment by thomasnield** [comment]
Hey! Here's an idea. Using workarounds like above can quickly become anti-reactive and excessively block I've discovered. Using operators like `last()` and `toList()` can get messy and cumbersome, undermining Rx's mission altogether. But what if there was an `isolateUpdates()` method in the `QueryUpdate.Builder`? This essentially would execute each INSERT individually without any BEGIN/END transaction mechanism batching them up? 

While this is not efficient, it may be effective for SQLite. 

```
 db.update("INSERT INTO TABLE_ONE (VALUE) VALUES (100)")
		.isolateUpdates()
                .returnGeneratedKeys()
                .getAs(Integer.class);
```

**Comment by davidmoten** [comment]
Hi Thomas
Excuse my quietness on this, I'm glad youve been working through it. 

I just had a look at http://stackoverflow.com/questions/10707434/sqlite-in-a-multithreaded-java-application which suggests reusing the same connection for all queries. You can do this now like this: 

```java
Database db = Database.from(connection);
````

or just using the url:

```java
Connection con = new ConnectionProviderFromUrl(url, username, password).get();
Database db = Database.from(con);
...
//when finished you'll need to manually close `con`:
con.close();
```

This discussion also makes me think that adding close hooks to `Database` would be nice:

```java
db.onClose(() -> con.close());
```

so that `Database.close()` can do more.

Can you try this singleton connection approach?

**Comment by thomasnield** [comment]
Okay making great strides, I think that worked. Thanks! But there is still one small (seemingly separate issue) that needs to be address...
```

import java.sql.Connection;

public final class Test {

    public static void main(String[] args) {

        Connection con = new ConnectionProviderFromUrl("jdbc:sqlite:C:/Users/Thomas/test.db").get();
        Database db = Database.from(con);

        db.update("INSERT INTO TABLE_ONE (VALUE) VALUES (100)")
                .returnGeneratedKeys()
                .getAs(Integer.class)
                .flatMap(k -> db.select("SELECT * FROM TABLE_ONE WHERE ID = ?")
                                .parameter(k)
                                .get(rs -> new Type1(rs.getInt("ID"), rs.getInt("VALUE")))
                ).flatMap(t1 -> db.update("INSERT INTO TABLE_TWO (FOREIGN_ID,VALUE) VALUES (?,?)")
                        .parameter(t1.id)
                        .parameter(t1.value)
                        .returnGeneratedKeys()
                        .getAs(Integer.class)
                ).flatMap(k -> db.select("SELECT * FROM TABLE_TWO WHERE ID = ?")
                        .parameter(k)
                        .get(rs -> new Type2(rs.getInt("ID"), rs.getInt("FOREIGN_ID"), rs.getInt("VALUE")))
                ).subscribe(System.out::println, Throwable::printStackTrace);

        db.close();
    }
    private static final class Type1 {
        private final int id;
        private final int value;
        private Type1(int id, int value) {
            this.id = id;
            this.value = value;
        }
    }
    private static final class Type2 {
        private final int id;
        private final int foreignId;
        private final int value;
        private Type2(int id, int foreignKey, int value) {
            this.id = id;
            this.foreignId = foreignKey;
            this.value = value;
        }
        @Override
        public String toString() {
            return "Type2{" +
                    "id=" + id +
                    ", foreignId=" + foreignId +
                    ", value=" + value +
                    '}';
        }
    }
}
```
The INSERTs happens successfully to both tables, but I then get this stack trace indicating the SQLITE_INTERRUPT was called by the client. 

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Type2{id=7, foreignId=7, value=100}
java.sql.SQLException: [SQLITE_INTERRUPT]  Operation terminated by sqlite3_interrupt() (interrupted)
	at org.sqlite.core.DB.newSQLException(DB.java:890)
	at org.sqlite.core.DB.newSQLException(DB.java:901)
	at org.sqlite.core.DB.throwex(DB.java:868)
	at org.sqlite.jdbc3.JDBC3ResultSet.next(JDBC3ResultSet.java:93)
	at com.github.davidmoten.rx.jdbc.QuerySelectProducer.processRow(QuerySelectProducer.java:112)
	at com.github.davidmoten.rx.jdbc.QuerySelectProducer.requestSome(QuerySelectProducer.java:75)
	at com.github.davidmoten.rx.jdbc.QuerySelectProducer.request(QuerySelectProducer.java:47)
	at rx.internal.operators.OperatorSubscribeOn$1$1$1$1.request(OperatorSubscribeOn.java:88)
	at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
	at rx.internal.operators.OperatorConcat$ConcatInnerSubscriber.setProducer(OperatorConcat.java:229)
	at rx.internal.operators.OperatorSubscribeOn$1$1$1.setProducer(OperatorSubscribeOn.java:81)
	at com.github.davidmoten.rx.jdbc.QuerySelectOnSubscribe.call(QuerySelectOnSubscribe.java:68)

```
The data seems to flow successfully throughout the chain as the `Type2` item gets printed by the subscriber. But it seems to have trouble closing the query without getting an interruption exception, which documentation says is called by the client. 
https://sqlite.org/rescode.html#interrupt

**Comment by thomasnield** [comment]
Okay and to make this issue more interesting, it seems to get interrupted after the first emission when I'm inserting multiple records

```
import com.github.davidmoten.rx.jdbc.ConnectionProviderFromUrl;
import com.github.davidmoten.rx.jdbc.Database;
import rx.Observable;

import java.sql.Connection;

public final class Test {

    public static void main(String[] args) {

        Connection con = new ConnectionProviderFromUrl("jdbc:sqlite:C:/Users/Thomas/test.db").get();
        Database db = Database.from(con);

        Observable<Integer> inputs = Observable.just(100,200,300);

        db.update("INSERT INTO TABLE_ONE (VALUE) VALUES (?)")
                .parameters(inputs)
                .returnGeneratedKeys()
                .getAs(Integer.class)
                .flatMap(k -> db.select("SELECT * FROM TABLE_ONE WHERE ID = ?")
                                .parameter(k)
                                .get(rs -> new Type1(rs.getInt("ID"), rs.getInt("VALUE")))
                ).flatMap(t1 -> db.update("INSERT INTO TABLE_TWO (FOREIGN_ID,VALUE) VALUES (?,?)")
                        .parameter(t1.id)
                        .parameter(t1.value)
                        .returnGeneratedKeys()
                        .getAs(Integer.class)
        ).flatMap(k -> db.select("SELECT * FROM TABLE_TWO WHERE ID = ?")
                        .parameter(k)
                        .get(rs -> new Type2(rs.getInt("ID"), rs.getInt("FOREIGN_ID"), rs.getInt("VALUE")))
        ).subscribe(System.out::println, Throwable::printStackTrace);

        db.close();
    }
    private static final class Type1 {
        private final int id;
        private final int value;
        private Type1(int id, int value) {
            this.id = id;
            this.value = value;
        }
    }
    private static final class Type2 {
        private final int id;
        private final int foreignId;
        private final int value;
        private Type2(int id, int foreignKey, int value) {
            this.id = id;
            this.foreignId = foreignKey;
            this.value = value;
        }
        @Override
        public String toString() {
            return "Type2{" +
                    "id=" + id +
                    ", foreignId=" + foreignId +
                    ", value=" + value +
                    '}';
        }
    }
}
````

**Comment by thomasnield** [comment]
fyi I created a repo for this https://github.com/thomasnield/rxjava_sqlite_test

**Comment by thomasnield** [comment]
A little theory: each query is "interrupting" the previous one... hence why the first item goes through but it leaves a trail of interrupted queries behind it to execute the current one. 

```
QUERY OP 3------------------O-----
QUERY OP 2-------------O---X-----
QUERY OP 1-------O----X----------
```

**Comment by thomasnield** [comment]
I posted something on SO as I'm guessing I'll need help from SQLite folks. http://stackoverflow.com/questions/33287173/sqlite-does-not-like-reactive-programming/33288169#33288169

**Comment by thomasnield** [comment]
I think there is no way around this considering the architecture of SQLite. I've learned the best way to deal with this is for every query operation to be followed with `toList().concatMap(Observable::from)` the result before handing it off to the next query in the chain or the client. I can close this PR but we may want to document this somewhere for SQLite users. I can do that if you feel that would be helpful.

**Comment by davidmoten** [comment]
Interesting. I read the SO post and sounds like your `toList().concatMap(Observable::from)` is the only solution.

**Comment by thomasnield** [comment]
Yeah I think so. I'll close this issue

**Comment by thomasnield** [comment]
Let me know if you want to document this on the Readme, and thanks for your help on this. Your singleton connection solution was necessary to rid half the problem.

**Comment by davidmoten** [comment]
No worries, small help only. A paragraph on use with SQLLite would be a
great addition to the README.md. Perhaps right at the bottom?

**Comment by thomasnield** [comment]
Exactly my thoughts. Thanks again, ill take care of today.
________________________________
