### ISSUE TITLE
Conflict between Lombok and autoMap

### ISSUE THREAD

**Issue by DarekDan** [davidmoten/rxjava-jdbc#83]
First let me state how excited I am to have found this reactive extension for JDBC. It works great and faster than processing with result sets. I have identified a minor problem with it. I am a big fan of the Lombok Project, especially with it's `@Data` feature (https://projectlombok.org/features/Data). However, it seems that `rxjava-jdbc` is unable to map constructors created by it. Here is an example:

```    
    @Data
    private class Customer {
       private final String Id;
       @NonNull private String Name;
    }
```
This creates a constructor like so:

```
        public Customer(String Id, @NonNull String Name) {
            if (Name == null) {
                throw new NullPointerException("Name");
            } else {
                this.Id = Id;
                this.Name = Name;
            }
        }
```
Given this code:

```
    @Test
    public void MustBeAbleToSelectReactive() {
        Database db = Database.from(connectionString);
        Observable<List<Customer>> set = db.select(selectNames).fetchSize(1000)
                .autoMap(Customer.class)
//                .get(r->new Customer(r.getString("ID"), r.getString("Name")))
                .buffer(10).asObservable();
        set.subscribe(list -> System.out.println(String.join(",", list.stream().map(c -> c.toString()).collect
                (Collectors.toList()))));
    }
```

I receive this error:

`rx.exceptions.OnErrorNotImplementedException: constructor with number of parameters=2  not found in class com.ddanielewski.learningspringboot.OracleTests$Customer`

As you can see yourself, there is a constructor with exactly two parameters. Am I doing something wrong here?

**Comment by DarekDan** [comment]
Here is the stacktrace ...

```
rx.exceptions.OnErrorNotImplementedException: constructor with number of parameters=2  not found in class com.ddanielewski.learningspringboot.OracleTests$Customer

	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.internal.operators.OperatorBufferWithSize$BufferExact.onError(OperatorBufferWithSize.java:121)
	at rx.observers.SerializedObserver.onError(SerializedObserver.java:152)
	at rx.observers.SerializedSubscriber.onError(SerializedSubscriber.java:78)
	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerError(OnSubscribeConcatMap.java:192)
	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerSubscriber.onError(OnSubscribeConcatMap.java:340)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onError(OperatorSubscribeOn.java:80)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:212)
	at com.github.davidmoten.rx.jdbc.QuerySelectProducer.handleException(QuerySelectProducer.java:142)
	at com.github.davidmoten.rx.jdbc.QuerySelectProducer.closeAndHandleException(QuerySelectProducer.java:98)
	at com.github.davidmoten.rx.jdbc.QuerySelectProducer.requestAll(QuerySelectProducer.java:61)
	at com.github.davidmoten.rx.jdbc.QuerySelectProducer.request(QuerySelectProducer.java:46)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber$1.request(OperatorSubscribeOn.java:109)
	at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerSubscriber.setProducer(OnSubscribeConcatMap.java:329)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.setProducer(OperatorSubscribeOn.java:105)
	at com.github.davidmoten.rx.jdbc.QuerySelectOnSubscribe.call(QuerySelectOnSubscribe.java:69)
	at com.github.davidmoten.rx.jdbc.QuerySelectOnSubscribe.call(QuerySelectOnSubscribe.java:20)
	at rx.Observable.unsafeSubscribe(Observable.java:10256)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)
	at rx.internal.operators.OperatorSubscribeOn.call(OperatorSubscribeOn.java:50)
	at rx.internal.operators.OperatorSubscribeOn.call(OperatorSubscribeOn.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10256)
	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.drain(OnSubscribeConcatMap.java:286)
	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.onNext(OnSubscribeConcatMap.java:144)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.observers.SerializedObserver.onNext(SerializedObserver.java:91)
	at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:94)
	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerNext(OnSubscribeConcatMap.java:182)
	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerScalarProducer.request(OnSubscribeConcatMap.java:366)
	at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.drain(OnSubscribeConcatMap.java:278)
	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.onNext(OnSubscribeConcatMap.java:144)
	at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.slowPath(OnSubscribeFromArray.java:100)
	at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:63)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
	at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10256)
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94)
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42)
	at rx.Observable.unsafeSubscribe(Observable.java:10256)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10256)
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94)
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10352)
	at rx.Observable.subscribe(Observable.java:10319)
	at rx.Observable.subscribe(Observable.java:10124)
	at com.ddanielewski.learningspringboot.OracleTests.MustBeAbleToSelectReactive(OracleTests.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.RuntimeException: constructor with number of parameters=2  not found in class com.ddanielewski.learningspringboot.OracleTests$Customer
	at com.github.davidmoten.rx.jdbc.Util.autoMap(Util.java:287)
	at com.github.davidmoten.rx.jdbc.Util$2.call(Util.java:260)
	at com.github.davidmoten.rx.jdbc.QuerySelectProducer.processRow(QuerySelectProducer.java:115)
	at com.github.davidmoten.rx.jdbc.QuerySelectProducer.requestAll(QuerySelectProducer.java:56)
	... 69 more
```

**Comment by DarekDan** [comment]
Never mind .. there is a weird issue when the class is private and local to the test. Once I moved it out, it works fine.
